package fxRekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

import fxRekisteri.*;
import rekisteri.Hyvaksyja;

/**
 * Test class made by ComTest
 * @version 24 Feb 2023 18:25:11 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RekisteriGUIControllerTest {



  // Generated by ComTest BEGIN
  /** 
   * testClone541 
   * @throws CloneNotSupportedException when error
   */
/*  @Test
  public void testClone541() throws CloneNotSupportedException {    // RekisteriGUIController: 541
    Hyvaksyja hyvaksyja = new Hyvaksyja(); 
    hyvaksyja.parse("   3  |  Merkki Esi   | 123"); 
    Hyvaksyja kopio = hyvaksyja.clone(); 
    assertEquals("From: RekisteriGUIController line: 546", hyvaksyja.toString(), kopio.toString()); 
    hyvaksyja.parse("   4  |  Merkki Eetu   | 123"); 
    assertEquals("From: RekisteriGUIController line: 548", false, kopio.toString().equals(hyvaksyja.toString())); 
  } // Generated by ComTest END
  */
}