package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

// Generated by ComTest END
import rekisteri.Balueet;
import rekisteri.Balue;
import rekisteri.SailoException;
import rekisteri.*;

/**
 * Test class made by ComTest
 * @version 19 Feb 2023 14:39:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class BalueetTest {



  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaaBalue192 
   * @throws SailoException when error
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testKorvaaTaiLisaaBalue192() throws SailoException,CloneNotSupportedException {    // Balueet: 192
    //Balueet balueet = new Balueet(); 
    //Balue alue1 = new Balue(); 
    //Balue alue2 = new Balue(); 
    //balue1.rekisteroi(); 
    //balue2.rekisteroi(); 
    //balueet.lisaa(alue1); 
    //balueet.korvaaTaiLisaaBalue(balue2); 
    //assertEquals("From: Balueet line: 201", 2, balueet.getBalueet()); 
    //balueet.korvaaTaiLisaaBalue(alue1); 
    //assertEquals("From: Balueet line: 203", 2, balueet.getBalueet()); 
  } // Generated by ComTest END
}