package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

// Generated by ComTest END
import rekisteri.Balue;
import rekisteri.*;

/**
 * Test class made by ComTest
 * @version 19 Feb 2023 16:00:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class BalueTest {


  // Generated by ComTest BEGIN
  /** 
   * testClone25 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone25() throws CloneNotSupportedException {    // Balue: 25
    //Balue eppu = new Balue(); 
    //eppu.setNimi("balue1"); 
    //Balue toppu = eppu.clone(); 
    //assertEquals("From: Balue line: 30", toppu.getBalueNimi(), eppu.getBalueenNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString61 */
  @Test
  public void testToString61() {    // Balue: 61
    Balue balue = new Balue(); 
    //Balue.parse("   1  |  1b    |"); 
    assertEquals("From: Balue line: 64", true, balue.toString().startsWith("1|1b|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi84 */
  @Test
  public void testRekisteroi84() {    // Luokka: 84
    Balue b = new Balue(); 
    b.rekisteroi(); 
    Balue a = new Balue(); 
    a.rekisteroi(); 
    //int n1 = b.getBalueenId(); 
    //int n2 = a.getBalueenId(); 
    //assertEquals("From: Balue line: 91", 1, n1); 
    //assertEquals("From: Balue line: 92", 2, n2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse154 */
  @Test
  public void testParse154() {    // Luokka: 154
    Balue balue = new Balue(); 
    balue.parse("  2  |  2a  |"); 
    assertEquals("From: Balue line: 157", "2|2a|", balue.toString()); 
    Balue balue2 = new Balue("2a"); 
    balue2.parse("  0  |  2a  |"); 
    assertEquals("From: Balue line: 160", "0|2a|", balue2.toString()); 
    Balue balue3 = new Balue("3a"); 
    balue3.parse("   1    |   3a|"); 
    assertEquals("From: Balue line: 163", "1|3a|", balue3.toString()); 
  } // Generated by ComTest END
}