package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

// Generated by ComTest END
import rekisteri.Hyvaksyja;
import rekisteri.*;

/**
 * Test class made by ComTest
 * @version 19 Feb 2023 12:49:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HyvaksyjatTest {


  // Generated by ComTest BEGIN
  /** testAnna49 */
  /*@Test
  public void testAnna49() {    // Hyvaksyja: 49
    Hyvaksyja hyvaksyja = new Hyvaksyja(); 
    hyvaksyja.setKentta(2, "Aatu"); 
    assertEquals("From: Hyvaksyja line: 52", "Aatu", hyvaksyja.anna(2)); 
  } // Generated by ComTest END
  */


  // Generated by ComTest BEGIN
  /** testRekisteroi209 */
  @Test
  public void testRekisteroi209() {    // Hyvaksyja: 209
//    Hyvaksyja esi1 = new Hyvaksyja(); 
//    assertEquals("From: Hyvaksyja line: 211", 0, esi1.getHyvaksyjaId()); 
//    esi1.rekisteroi(); 
//    Hyvaksyja esi2 = new Hyvaksyja(); 
//    esi2.rekisteroi(); 
//    int n1 = esi1.getHyvaksyjaId(); 
//    int n2 = esi2.getHyvaksyjaId(); 
//    assertEquals("From: Hyvaksyja line: 217", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString271 */
 /* @Test
  public void testToString271() {    // Hyvaksyja: 271
    Hyvaksyja hyvaksyja = new Hyvaksyja(); 
    hyvaksyja.parse("  1  |  0  | Jukka | Poika | 030201-111C | poika | Paatie | 40100 | 0123456 | kala | evlut | Jake Poika | 456456678 | jakepoika@email.fi | Jaana Poika | 123123456 | jaanapoika@email.com"); 
    assertEquals("From: Hyvaksyja line: 274", true, hyvaksyja.toString().startsWith("1|0|Jukka|Poika|030201-111C|")); 
  } 
  */


  // Generated by ComTest BEGIN
  /** 
   * testClone304 
   * @throws CloneNotSupportedException when error
   */
  /*@Test
  public void testClone304() throws CloneNotSupportedException {    // Hyvaksyja: 304
    Hyvaksyja eppu = new Hyvaksyja(); 
    eppu.setEnimi("heppu"); 
    Hyvaksyja toppu = eppu.clone(); 
    assertEquals("From: Hyvaksyja line: 309", toppu.getEnimi(), eppu.getEnimi()); 
  } // Generated by ComTest END
  */


  // Generated by ComTest BEGIN
  /** testParse352 */
  /*@Test
  public void testParse352() {    // Hyvaksyja: 352
    Hyvaksyja hyvaksyja = new Hyvaksyja(); 
    hyvaksyja.parse("  1  |   2   |  Mikko  |  Tikkanen  |  123-BCNF  |  Poika  |  Jokutie 4  |  4300  |  +345 111  |  Omena  |  ev.lut  |  Marko Jarvi  |  +357 444  |  Marko.sapo.fi  |  Minna Jarvi  |  +357 123  |  Minna.sapo.fi  |"); 
    assertEquals("From: Hyvaksyja line: 355", "1|2|Mikko|Tikkanen|123-BCNF|Poika|Jokutie 4|4300|+345 111|Omena|ev.lut|Marko Jarvi|+357 444|Marko.sapo.fi|Minna Jarvi|+357 123|Minna.sapo.fi|", hyvaksyja.toString()); 
  } // Generated by ComTest END
  */
}