package rekisteri.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;

// Generated by ComTest END
//import rekisteri.Yhtio;
import rekisteri.Balueet;
import rekisteri.Balue;
import rekisteri.Hyvaksyjat;
import rekisteri.Hyvaksyja;
import rekisteri.SailoException;
import rekisteri.*;

/**
 * ottok
 * Test class made by ComTest
 * @version 19 Feb 2023 15:29:43 // Generated by ComTest
 *
 */
/*@SuppressWarnings({ "all" })
public class YhtioTest {


  // Generated by ComTest BEGIN  // Yhtio: 27
   //private Yhtio yhtio; 

/*
    private Hyvaksyjat hyvaksyjat = new Hyvaksyjat(); 
    private Balueet balueet = new Balueet(); 

   private Hyvaksyja aku1; 
   private Hyvaksyja aku2; 
   private Balue ykkonen; 
   private Balue kakkonen; 
*/


/*
     public void alustaYhtio() {
     yhtio = new Yhtio(); 
     ykkonen = new Balue(); ykkonen.rekisteroi(); ykkonen.taytaEsiTiedoilla(); 
     kakkonen = new Balue(); kakkonen.rekisteroi(); kakkonen.taytaEsiTiedoilla(); 
     aku1 = new Hyvaksyja(); aku1.rekisteroi(); aku1.taytaEsiTiedoilla(); 
     aku2 = new Hyvaksyja(); aku2.rekisteroi(); aku2.taytaEsiTiedoilla(); 


     try {
     yhtio.lisaa(ykkonen); 
     yhtio.lisaa(kakkonen); 
     yhtio.lisaa(aku1); 
     yhtio.lisaa(aku2); 
       }

     catch ( Exception e) {
    System.err.println(e.getMessage()); 
    }
    }

*/
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista85 
   * @throws Exception when error
   */
//  @Test
//  public void testPoista85() throws Exception {    // Yhtio: 85
//    alustaYhtio(); 
//    assertEquals("From: Yhtio line: 88", 1, yhtio.poista(aku1)); 
//  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa123 
   * @throws SailoException when error
   */
//  @Test
//  public void testLisaa123() throws SailoException {    // Yhtio: 123
//    Yhtio yhtio = new Yhtio(); 
//    Hyvaksyja aku1 = new Hyvaksyja(), aku2 = new Hyvaksyja(); 
//    aku1.rekisteroi(); aku2.rekisteroi(); 
//    assertEquals("From: Yhtio line: 128", 0, yhtio.getHyvaksyjia()); 
//    yhtio.lisaa(aku1); assertEquals("From: Yhtio line: 129", 1, yhtio.getHyvaksyjia()); 
//    yhtio.lisaa(aku2); assertEquals("From: Yhtio line: 130", 2, yhtio.getHyvaksyjia()); 
//    yhtio.lisaa(aku1); assertEquals("From: Yhtio line: 131", 3, yhtio.getHyvaksyjia()); 
//    assertEquals("From: Yhtio line: 132", 3, yhtio.getHyvaksyjia()); 
//    assertEquals("From: Yhtio line: 133", aku1, yhtio.getHyvaksyja(0)); 
//    assertEquals("From: Yhtio line: 134", aku2, yhtio.getHyvaksyja(1)); 
//    assertEquals("From: Yhtio line: 135", aku1, yhtio.getHyvaksyja(2)); 
//    try {
//    assertEquals("From: Yhtio line: 136", aku1, yhtio.getHyvaksyja(3)); 
//    fail("Yhtio: 136 Did not throw IndexOutOfBoundsException");
//    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
//    yhtio.lisaa(aku1); assertEquals("From: Yhtio line: 137", 4, yhtio.getHyvaksyjia()); 
//    yhtio.lisaa(aku1); assertEquals("From: Yhtio line: 138", 5, yhtio.getHyvaksyjia()); 
//  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa162 
   * @throws SailoException when error
   */
  /*@Test
  public void testKorvaaTaiLisaa162() throws SailoException {    // Yhtio: 162
    alustaYhtio(); 
    assertEquals("From: Yhtio line: 165", 2, yhtio.etsi("*",0).size()); 
    yhtio.korvaaTaiLisaa(aku1); 
    assertEquals("From: Yhtio line: 167", 2, yhtio.etsi("*",0).size()); 
  } // Generated by ComTest END

*/
  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta197 
   * @throws SailoException when error
   */
 /* @Test
  public void testLueTiedostosta197() throws SailoException {    // Yhtio: 197
    String hakemisto = "testikelmit"; 
    File dir = new File(hakemisto); 
    File ftied  = new File(hakemisto+"/hyvaksyjat.dat");     //hyvaksyjat.dat
    File fhtied = new File(hakemisto+"/balueet.dat");    //balueet.dat
    dir.mkdir(); 
    ftied.delete(); 
    fhtied.delete(); 
    alustaYhtio(); 
    yhtio.tallenna(hakemisto); 
    yhtio = new Yhtio(); 
    yhtio.lueTiedostosta(hakemisto); 
    Collection<Hyvaksyja> kaikki = yhtio.etsi("",-1); 
    Iterator<Hyvaksyja> it = kaikki.iterator(); 
    Hyvaksyja op1 = it.next(); 
    Hyvaksyja op2 = it.next(); 
    assertEquals("From: Yhtio line: 217", true, op1.equals(aku1)); 
    assertEquals("From: Yhtio line: 218", true, op2.equals(aku2)); 
    assertEquals("From: Yhtio line: 219", false, it.hasNext()); 
    yhtio.lisaa(aku2); 
    yhtio.tallenna();  // tekee molemmista .bak
    assertEquals("From: Yhtio line: 222", true, ftied.delete()); 
    assertEquals("From: Yhtio line: 223", true, fhtied.delete()); 
    assertEquals("From: Yhtio line: 224", true, dir.delete()); 
  } // Generated by ComTest END
*/

  // Generated by ComTest BEGIN
  /** 
   * testMontakoHyvaksyjaa384 
   * @throws SailoException when error
   */
  /*@Test
  public void testMontakoHyvaksyjaa384() throws SailoException {    // Yhtio: 384
    alustaYhtio(); 
    //assertEquals("From: Yhtio line: 387", 2, yhtio.montakoHyvaksyjaa()); 
  } // Generated by ComTest END
}*/